### ISSUE TITLE
User DN format question

### ISSUE THREAD

**Issue by ArthurMitchell42** [wiltonsr/ldapAuth#14]
I'm just starting with this great plugin but have a question.
The DN format when querying is uid=USERNAME,dn=example,dn=com
but my LDAP server requires uid=USERNAME,cn=user,dn=example,dn=com
is there a way to manipulate the query sting to support the server please?

**Comment by wiltonsr** [comment]
Hello @ArthurMitchell42,

Just configure `baseDN=cn=user,dc=example,dc=com`.

You can check more details on the [examples](https://github.com/wiltonsr/ldapAuth/tree/master/examples) page.

Let me know if you have any problems with the configs.

**Comment by ArthurMitchell42** [comment]
Thank you Wilton, that's a great help.
I have it all working nicely from the services.yml file now, just one detail I can't figure out, the **allowedGroups** attribute says it wants the group DN but when I add one it interprets each element of the DN as a different group. Just putting **Traefik_Admins** in instead of the full DN (**cn=Traefik_Admins,,cn=groups,dc=example,dc=com**) also fails. The logs show below:

<pre>
INFO: ldapAuth: 2022/09/30 17:11:16 restricted.go:51: Authenticating User: uid=uuuuu,cn=users,dc=example,dc=com
DEBUG: ldapAuth: 2022/09/30 17:11:16 restricted.go:51: Searching Group: 'cn=Traefik_Admins' with User: 'uid=uuuuu,cn=users,dc=example,dc=com'
DEBUG: ldapAuth: 2022/09/30 17:11:16 restricted.go:51: Searching Group: 'cn=groups' with User: 'uid=uuuuu,cn=users,dc=example,dc=com'
DEBUG: ldapAuth: 2022/09/30 17:11:16 restricted.go:51: Searching Group: 'dc=example' with User: 'uid=uuuuu,cn=users,dc=example,dc=com'
DEBUG: ldapAuth: 2022/09/30 17:11:16 restricted.go:51: Searching Group: 'dc=click' with User: 'uid=uuuuu,cn=users,dc=example,dc=com'
ERROR: ldapAuth: 2022/09/30 17:11:16 restricted.go:51: %!s(<nil>)</pre>

I've tried escaping the commas with {{ }} but it still interprets the DN as a list.
Arthur

**Comment by ArthurMitchell42** [comment]
Thank you Wilton, I have it all working splendidly now from the services.yml file, including allowed groups.

**Comment by wiltonsr** [comment]
Glad to know.
