### ISSUE TITLE
Support TLS LDAP Server

### ISSUE THREAD

**Issue by wiltonsr** [wiltonsr/ldapAuth#2]
Create a `startTLS`option.

*Optional, Default=false*

It will instructs ldapAuth to issue a [StartTLS](https://tools.ietf.org/html/rfc4511#section-4.14) request when initializing the connection with the LDAP server.

**Comment by miconx** [comment]
same here would need to connect via starttls

**Comment by wiltonsr** [comment]
The following options should be available:

`insecureSkipVerify`

*Optional, Default=false*

`certificateAuthority`

*Optional, Default=""*

**Comment by wiltonsr** [comment]
Hi, @miconx 

Let me know if there is some problem with this feature.
