### ISSUE TITLE
Support AllowedGroups

### ISSUE THREAD

**Issue by wiltonsr** [wiltonsr/ldapAuth#3]
Create a `allowedGroups` option.

*Optional, Default=""*

It will be a list of LDAP group DNs that users could be members of to be granted access. If a user is in any one of the listed groups, then that user is granted access.

If setted to an empty list or nil will allow all users that have an LDAP account to log in, without performing any group membership checks.

Unfortunately, traefik's option parser does not work with elements containing commas, which is the case with LDAP groups. So this issue will be suspended until we have a definition of the [issue](https://github.com/traefik/paerser/issues/9).

**Comment by github-479** [comment]
Awesome feature. The linked issue was marked as closed and fixed merged a few days ago.

**Comment by wiltonsr** [comment]
Unfortunately, the `traefik paerser` still doesn't understand options with commas.

So, this feature will need to wait a little bit more.

**Comment by Daiyousei** [comment]
Hi ! 
Do we still have a blocking issue on Traefik side, or should we create one ?

**Comment by XarkaOfMahrak** [comment]
Hi !

Seems they merged a new fix https://github.com/traefik/paerser/pull/11

**Comment by wiltonsr** [comment]
Hello, everyone.

I'm waiting for a `traefik`'s release with `paerser`'s fix to start adding this functionality.

As soon as possible I will come back with news.

**Comment by wiltonsr** [comment]
Confirmed that `traefik v2.8.2` with `paerser v0.1.6 ` works as expected.

```log
traefik  | DEBUG: ldapAuth: 2022/08/12 18:06:09 restricted.go:51: AllowedGroups => '[ou=mathematicians,dc=example,dc=com ou=italians,ou=scientists,dc=example,dc=com ou=new italians,ou=scientists,dc=example,dc=com]'
```

I will start to work on this functionality now.

**Comment by wiltonsr** [comment]
@github-479 @XarkaOfMahrak 

Let me know if there is any problem with this functionality.

**Comment by XarkaOfMahrak** [comment]
Hey, 

I completely forgot to say, but yep, this fix the issue !

Many thanks !
