### ISSUE TITLE
I don't find syntax for "allowedGroup"

### ISSUE THREAD

**Issue by raspberry1704** [wiltonsr/ldapAuth#36]
Hello,

Firstly, this plugin is really great. It helped me for my authent with ldap and specially with filtering by username.

Now, I want to integrate my ldap groups. I tried a lot of syntaxes but it's not working.

Here is a example of what I tried with the parameter "allowedGroups": 

 - "traefik.http.middlewares.ldap-auth.plugin.ldapAuth.allowedGroups=[cn=MY_GROUP,ou=groups,dc=MY_DOMAIN,dc=fr]"

And thousands others tests...

Please, could you help me ? 

Have a nice day.
Raspberry

**Comment by wiltonsr** [comment]
Hello, @raspberry1704 

`allowedGroups` is not supported with labels, because multiple value labels are separated with commas. 

You can use `yaml` or `toml` configuation files. Please check the examples folder.
