### ISSUE TITLE
[Bug] Apostrophe in user DN fails to match allowed groups

### ISSUE THREAD

**Issue by fcinqmars** [wiltonsr/ldapAuth#50]
I have a user that has an apostrophe in their last name causing the LDAP filter for group matching to fail. The reason behind it is that the Go templating uses HTML templates and outputs the resulting filter as:

`(|(member=CN=First N&#39;ame,OU=Users,OU=Company,DC=test,DC=local)(uniqueMember=CN=First N&#39;ame,OU=Users,OU=Company,DC=test,DC=local)(memberUid=fname))'`

The filter should read: `(|(member=CN=First N'ame,OU=Users,OU=Company,DC=test,DC=local)(uniqueMember=CN=First N'ame,OU=Users,OU=Company,DC=test,DC=local)(memberUid=fname))'`

As per above, the apostrophe (') is escaped to `&#39;`.

**Comment by wiltonsr** [comment]
Fixed by #51
