### ISSUE TITLE
Username header does not get set on subsequent requests

### ISSUE THREAD

**Issue by sseemayer** [wiltonsr/ldapAuth#57]
Thanks a lot for this super-useful plugin!

The `ForwardUsername` setting works fine for the first request passed through the ldapAuth middleware, but will not get forwarded for subsequent requests.

Steps to reproduce:

  1. Enable `ForwardUsername` in the middleware config
  2. Authenticate with a request that is behind the ldapAuth middleware. Using `traefik/whoami` as the secured service works great for troubleshooting
  3. Observe that the username header is set as expected.
  4. Refresh the page to re-send the request
  5. The username header is not set anymore.

I will contribute a PR fixing this issue in a moment.

**Comment by sseemayer** [comment]
#56 would also resolve my issue, so I would be fine if that got merged instead of #57

**Comment by wiltonsr** [comment]
Available in [v0.1.6](https://github.com/wiltonsr/ldapAuth/releases/tag/v0.1.6).
