### ISSUE TITLE
BindDN and BindPassword are not used for AllowedGroups checking

### ISSUE THREAD

**Issue by sasjafor** [wiltonsr/ldapAuth#61]
When using the options `BindDN` and `BindPassword` in combination with `AllowedGroups` then the `AllowedGroups` are checked using the user credentials instead of the bind credentials.

Is this intentional behaviour?

For me this creates an issue since the individual users cannot access group membership information. Only the bind user has access to those parts of the directory.

If it's unintentional, consider this a bug report. If it's intentional, then a feature request for a toggle to choose the behaviour.

**Comment by wiltonsr** [comment]
Hi, @sasjafor 

Could you provide your confs and `debug logs`?



> When using the options `BindDN` and `BindPassword` in combination with `AllowedGroups` then the `AllowedGroups` are checked using the user credentials instead of the bind credentials.
> 
> Is this intentional behaviour?

Please check [Operations Mode](https://github.com/wiltonsr/ldapAuth?tab=readme-ov-file#operations-mode) docs. All subsequent `LDAP` operations will be performed based on the `Operation Mode` defined in confs. You can also check this mode by checking `ldapAuth`'s logs.

You can also check this [example](https://github.com/wiltonsr/ldapAuth?tab=readme-ov-file#search-mode-authenticated-example). I think you need to set [searchFilter](https://github.com/wiltonsr/ldapAuth?tab=readme-ov-file#searchfilter) option to perform what you need.

**Comment by sasjafor** [comment]
I added 

`conn.Bind(la.config.BindDN, la.config.BindPassword)` 

before `LdapCheckUserAuthorized` is called and that fixed my problem.

https://github.com/wiltonsr/ldapAuth/blob/5de938dfa1b7d8c5746e8a11cdc4f2f33155b27b/ldapauth.go#L194-L202

**Comment by wiltonsr** [comment]
> Yes, `SearchMode` is called, but later in `LdapCheckUser` a bind is performed again also using the user credentials:

You are right, thanks for pointing that.

I created a [new branch](https://github.com/wiltonsr/ldapAuth/tree/fix-issue-61) with a fix. Could you test cloning this repository? If this works for you I will release a new version.

**Comment by wiltonsr** [comment]
Available in [v0.1.8](https://github.com/wiltonsr/ldapAuth/releases/tag/v0.1.8).

**Comment by sasjafor** [comment]
I tested and now it works as expected. Thanks for the quick fix!
